### ISSUE TITLE
Very slow on Safari browser

### ISSUE THREAD

**Issue by Emasoft** [lo-th/3d.city#1]
Cool, but it seems to have problems with Safari. It is too slow to be usable (my Safari version is 7.0.5, OS X 10.9.4). It is well below 1 FPS, and it hangs often. It works fine with Chrome v35.0.1916.153 on the same computer. There must be something related to the specific WebGL implementation in Safari.

**Comment by lo-th** [comment]
hum strange but i can't test safari.
webgl on safari is young,
i use no light no complex shader, but lot of geometry rebuild.
or is maybe ground tranparency. 

you can test this http://jsdo.it/clockmaker/threejs-marge
tell me if you see big differency between safari and chrome

**Comment by calvinmetcalf** [comment]
that link works fine in chrome but in safari:

``` js
[Error] Error creating WebGL context.
    WebGLRenderer (js, line 388)
```

**Comment by Emasoft** [comment]
WebGL works fine in Safari. Maybe you have it disabled. Check if you have the WebGL option enabled in the Develop menu:
![develop_menu-e1343246676784](https://cloud.githubusercontent.com/assets/713559/3843443/606d267c-1e40-11e4-8059-942dbf26f4a3.jpg)

**Comment by calvinmetcalf** [comment]
yup forgot to enable it, demo then works in safari, though while it goes at the same speed it flickers a lot in a way it doesn't in chrome.

**Comment by lo-th** [comment]
update with last three dev version i hope is better
