### ISSUE TITLE
Cannot read property 'vertexNormals' of undefined

### ISSUE THREAD

**Issue by ChrisCinelli** [lo-th/3d.city#12]
After a little bit of playing, I cannot build anymore and everything I try I get::
13three.min.js:183 Uncaught TypeError: Cannot read property 'vertexNormals' of undefined
three.min.js:183 Uncaught TypeError: Cannot read property 'vertexNormals' of undefinedthree.min.js:183 THREE.BufferGeometry.fromGeometryview.min.js:45 V3D.Base.rebuildTreeLayerview.min.js:44 V3D.Base.removeTreePackview.min.js:58 V3D.Base.buildview.min.js:9 cityWorker.onmessage

**Comment by lo-th** [comment]
yes is same error than disapper 
normaly is ok now
