### ISSUE TITLE
Trains going sideways when on water

### ISSUE THREAD

**Issue by xenyal** [lo-th/3d.city#15]
Although it was amusing, don't think that's expected behavior haha. Check out this screenshot:
![image](https://cloud.githubusercontent.com/assets/1797007/5239089/3ab538fa-78a1-11e4-8a7f-414fb59579bf.png)

**Comment by waldoj** [comment]
Can confirm—that happens every time for me, too.

**Comment by lo-th** [comment]
underwater train hidden
