### ISSUE TITLE
track issues

### ISSUE THREAD

**Issue by splace** [lo-th/3d.city#20]
track over water not joining up

erasing track not updating surrounding track

![screenshot from 2015-01-21 00 59 12](https://cloud.githubusercontent.com/assets/1234848/5829383/59764668-a109-11e4-9cb3-92eca3c63bad.png)

**Comment by splace** [comment]
just noitcsed, same with road.

**Comment by splace** [comment]
and now realize they become bridges, and are only available in straight lines.

**Comment by splace** [comment]
if you're interested, i can make the tile set more distinctive for the bridges?

based on this;  http://www.oocities.org/timessquare/3806/simcity2/images/tip2.gif

**Comment by lo-th** [comment]
yep i have to make 3d model
bridge is only  straight lines
