### ISSUE TITLE
tiles not cut from png file correctly

### ISSUE THREAD

**Issue by splace** [lo-th/3d.city#25]
![screenshot from 2015-01-23 00 11 23](https://cloud.githubusercontent.com/assets/1234848/5867611/61b15cee-a296-11e4-95d7-7f38fbbdb887.png)

where the power crosses track the tiles seem to be one pixel out, and one has part of the other in it, this can't be a problem with the tiles32.png file, and i think is probably an issue with the calculation of where pixels are within the tile map.

**Comment by lo-th** [comment]
correct
