### ISSUE TITLE
Crime rates not calculating properly?

### ISSUE THREAD

**Issue by brycekmartin** [lo-th/3d.city#4]
The city seems to always have a huge crime issue.  You can add tons of police stations, far more than one would expect, but still have high crime reported as an issue. See the HN reference as a potential fix. https://news.ycombinator.com/item?id=8147471

**Comment by lo-th** [comment]
yes i try but don't resolve the probleme 
i think make different map for see zone effect like java version

**Comment by smichaelsen** [comment]
I'm also experiencing this.

**Comment by lo-th** [comment]
is done :)
