### ISSUE TITLE
Violates GPL V3 License

### ISSUE THREAD

**Issue by graememcc** [lo-th/3d.city#7]
All files in the src/ directory are taken from https://github.com/graememcc/micropolisjs, with various minor modifications.

micropolisJS is licensed under the GPLv3, and as such contains a LICENSE file, a COPYING file, and copyright headers at the start of every other file. The GPLv3 requires that any modifications should also contain the GPL license, COPYING file, and must preserve the copyright headers from the original source.

The GPL license and copyright headers from micropolisJS have been stripped from the files in the src directory which violates the licensing terms. They must be restored.

**Comment by lo-th** [comment]
Yes your right, i add licence 
hope you like my version
