### ISSUE TITLE
Zones Disappear

### ISSUE THREAD

**Issue by Redoubts** [lo-th/3d.city#9]
After a certain amount of time, new zones are suddenly no longer visible. Saving and opening again in a new tab seems to help, until it doesn't.

Now after a "reset", even previously visible zones are gone. This land was fully populated before, and the traffic suggests it's fully populated now despite being invisible.

![untitled-1](https://cloud.githubusercontent.com/assets/2435101/5232827/5eeff23c-7711-11e4-8f78-e8a2e80c2dbf.png)

**Comment by bozzmedia** [comment]
Similar experience.  Using Firefox / Win7

**Comment by lo-th** [comment]
is better now , i update geometry

**Comment by bozzmedia** [comment]
Remains an issue on a previously saved map.  will start a new map and see how it goes. thanks!
